/*
 * Companion Bots — corpse looting for autonomous bots (TrinityCore master, retail 12.0.7).
 *
 * Until now bots killed things and walked away from the bodies. That is wrong three times over:
 * a player always loots, the bot never earns a copper, and — the reason this blocks questing —
 * every "collect N of X" objective is completed by LOOTING the corpse, not by the kill. Without
 * this, that whole class of quest can never finish.
 *
 * The corpse's loot is generated by the engine on death exactly as it is for a real kill; all this
 * does is what the client would do with the loot window: take the money, then take each slot.
 */

#ifndef TRINITYCORE_PBOT_LOOT_H
#define TRINITYCORE_PBOT_LOOT_H

#include "Define.h"
#include "ObjectGuid.h"

class Player;

namespace PbotLoot
{
    // Corpses further than this are somebody else's problem. Kept short — this is meant to pick up
    // what the bot itself just killed, not to send it touring the zone looting other people's kills
    // (which it could not loot anyway).
    constexpr float SEARCH_RANGE = 40.0f;

    // Walks to and empties one lootable corpse. Returns true when it took over the tick.
    //
    // walkMs bounds the walk: a corpse on the far side of terrain the pathfinder will not cross
    // would otherwise hold the bot in place until the body decayed, because this returns "busy"
    // every tick while it keeps failing to arrive.
    bool Tick(Player* bot, ObjectGuid& corpseGuid, uint32& cooldownMs, uint32& walkMs, uint32 diff);
}

#endif // TRINITYCORE_PBOT_LOOT_H
